# Generated by Django 6.0.4 on 2026-04-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_ingrediente_descricao_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira 1', max_length=50, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='cosmetics.produto')),
            ],
        ),
    ]
