# Generated by Django 6.0.4 on 2026-04-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cor_borda', models.CharField(default='#6b0c22', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
